select = [
    "E",  # pycodestyle (error)
    "W",  # pycodestyle (warning)
    "D",  # pydocstyle
    "I",  # isort
    "ANN",  # flake8-annotations
    "DTZ",  # flake8-datetimez
]
ignore = [
    "ANN101",  # missing-type-self
    "ANN401",  # any-type
    "D100",  # undocumented-public-module
    "D101",  # undocumented-public-class
    "D105",  # undocumented-magic-method
    "D106",  # undocumented-public-nested-class
    "D203",  # one-blank-line-before-class
    "D213",  # multi-line-summary-second-line
    "D404",  # docstring-starts-with-this
    "D407",  # dashed-underline-after-section
]

exclude = [
    "build",
    "dist",
    "blossom/bootstrap/*",
    "*/migrations/*",
    "docker/*",
    "./local_settings.py",
]

line-length = 100  # Same as black

[per-file-ignores]
"test_*" = [
    "D",  # Disable documentation lints for test files
    "DTZ",  # Disable timezone lints for test files
]

[isort]
known-third-party = [
    "better_exceptions",
    "blossom_wrapper",
    "click",
    "django",
    "django_filters",
    "dotenv",
    "dpath",
    "drf_yasg",
    "ipware",
    "markdown",
    "mimesis",
    "opentelemetry",
    "praw",
    "prawcore",
    "psaw",
    "pytest",
    "pytest_django",
    "pytz",
    "pyuwsgi",
    "requests",
    "rest_framework",
    "rest_framework_api_key",
    "revproxy",
    "shiv",
    "slack",
    "social_core",
    "social_django",
    "stripe",
    "toml"
]
