---
version: '3'
services:
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_DB: 'local_blossom'
      POSTGRES_PASSWORD: 'this-is-not-prod-so-why-do-we-care'
      POSTGRES_USER: 'blossom_is_the_best'
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 5432:5432

  blossom:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/blossom.Dockerfile
    environment:
      ENVIRONMENT: local
      PORT: '8000'
      BLOSSOM_SECRET_KEY: 'imhenrytheeigthiam.henrytheeigthiamiam.igotmarriedtothewidownextdoor.shesbeenmarriedseventimesbefore'
      BLOSSOM_DB_DATABASE: 'local_blossom'
      BLOSSOM_DB_USERNAME: 'blossom_is_the_best'
      BLOSSOM_DB_PASSWORD: 'this-is-not-prod-so-why-do-we-care'
      BLOSSOM_DB_HOST: db  # Funky DNS stuff with docker-compose. See above service.
      BLOSSOM_DB_PORT: '5432'
      DJANGO_LOG_LEVEL: INFO
    volumes:
      - static:/app/blossom/static
      - ./blossom/settings:/app/blossom/settings:ro
      - ./docker/local_settings.py:/app/blossom/settings/local.py:ro

  http:
    depends_on:
      - blossom  # Because DNS needs to be there or this container fails
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/data/static:ro
    ports:
      - 8080:80

volumes:
  static:
