# Generated by Django 3.2.13 on 2022-04-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", editable=False, max_length=300),
        ),
    ]
