# Generated by Django 2.2.12 on 2020-05-06 17:21

import django.db.models.deletion
from django.db import migrations, models

import blossom.api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200506_0250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="source",
            field=models.ForeignKey(
                default=blossom.api.models.get_default_source,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Source",
            ),
        ),
    ]
