# Generated by Django 2.2.12 on 2020-08-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_submission_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="image_url",
            new_name="content_url",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="is_image",
        ),
    ]
