# Generated by Django 3.1.3 on 2020-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20200831_0335"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="removed_from_queue",
            field=models.BooleanField(default=False),
        ),
    ]
