# Generated by Django 3.2.3 on 2021-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_submission_cannot_ocr"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["url", "tor_url"], name="api_submiss_url_5225f1_idx"
            ),
        ),
    ]
