# Generated by Django 3.2.3 on 2021-06-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_submission_api_submiss_url_5225f1_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(fields=["author"], name="author_idx"),
        ),
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(fields=["submission"], name="submission_idx"),
        ),
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(fields=["original_id"], name="original_id_idx"),
        ),
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(fields=["url"], name="url_idx"),
        ),
    ]
