# Generated by Django 3.2.10 on 2022-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auto_20220116_2114"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
