# Generated by Django 3.2.12 on 2022-02-23 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0019_submission_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptionCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("comment_pending", "Comment Pending"),
                            ("comment_resolved", "Comment Resolved"),
                            ("warning_pending", "Warning Pending"),
                            ("warning_resolved", "Warning Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "internal_note",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "claim_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "complete_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.submission"
                    ),
                ),
            ],
        ),
    ]
