# Generated by Django 3.2.12 on 2022-02-26 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0022_alter_transcriptioncheck_transcription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcriptioncheck",
            name="moderator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
