# Generated by Django 3.2.12 on 2022-03-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_transcriptioncheck_moderator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcriptioncheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("comment_pending", "Comment Pending"),
                    ("comment_resolved", "Comment Resolved"),
                    ("comment_unfixed", "Comment Unfixed"),
                    ("warning_pending", "Warning Pending"),
                    ("warning_resolved", "Warning Resolved"),
                    ("warning_unfixed", "Warning Unfixed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
