# Generated by Django 3.2.15 on 2022-08-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_accountmigration"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="submission",
            name="api_submiss_url_5225f1_idx",
        ),
        migrations.RemoveIndex(
            model_name="transcription",
            name="author_idx",
        ),
        migrations.RemoveIndex(
            model_name="transcription",
            name="submission_idx",
        ),
        migrations.RemoveIndex(
            model_name="transcription",
            name="original_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="transcription",
            name="url_idx",
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["url"], name="submission_url_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["tor_url"], name="submission_tor_url_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["completed_by"], name="submission_completed_by_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["complete_time"], name="submission_complete_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["create_time"], name="submission_create_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(fields=["author"], name="transcription_author_idx"),
        ),
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(
                fields=["submission"], name="transcription_submission_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(
                fields=["original_id"], name="transcription_original_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(fields=["url"], name="transcription_url_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptioncheck",
            index=models.Index(fields=["status"], name="status_idx"),
        ),
    ]
