# Generated by Django 3.2.15 on 2022-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_auto_20220825_1917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="content_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="tor_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
