# Generated by Django 3.2.19 on 2023-05-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_auto_20221004_2042"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="feed",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
