# Generated by Django 2.2.11 on 2020-03-19 21:41

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(default=api.models.create_id, max_length=36)),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('redis_id', models.CharField(blank=True, max_length=12, null=True)),
                ('claim_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('complete_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('source', models.CharField(max_length=20)),
                ('url', models.CharField(blank=True, max_length=2083, null=True)),
                ('tor_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcription_id', models.CharField(max_length=36)),
                ('completion_method', models.CharField(max_length=20)),
                ('url', models.CharField(blank=True, max_length=2083, null=True)),
                ('text', models.TextField(blank=True, max_length=4294000000, null=True)),
                ('ocr_text', models.TextField(blank=True, max_length=4294000000, null=True)),
                ('removed_from_reddit', models.BooleanField(default=False)),
            ],
        ),
    ]
