# Generated by Django 2.2.11 on 2020-04-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200319_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submission_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submission_id',
            new_name='source_id',
        ),
        migrations.RenameField(
            model_name='transcription',
            old_name='transcription_id',
            new_name='source_id',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='completion_method',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='post_time',
        ),
    ]
