# Generated by Django 2.2.12 on 2020-04-26 04:57

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200425_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='source_id',
            new_name='original_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='source',
        ),
        migrations.AddField(
            model_name='submission',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transcription',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transcription',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transcription',
            name='source',
            field=models.ForeignKey(default=api.models.get_default_source, on_delete=django.db.models.deletion.CASCADE, to='api.Source'),
        ),
    ]
