# Generated by Django 2.2.12 on 2020-08-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_submission_is_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="original_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
