# Generated by Django 2.2.12 on 2020-04-26 05:04

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200426_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='source_id',
            new_name='original_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.ForeignKey(default=api.models.get_default_source, on_delete=django.db.models.deletion.CASCADE, to='api.Source'),
        ),
    ]
