# Generated by Django 2.2.12 on 2020-08-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20200822_0455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
