# Generated by Django 2.2.12 on 2020-04-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200426_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='ocr_text',
        ),
    ]
