# Generated by Django 2.2.12 on 2020-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_transcription_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='tor_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
