# Generated by Django 2.2.12 on 2020-08-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_source_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="id",
        ),
    ]
