# Generated by Django 2.2.12 on 2020-05-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200502_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='id',
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
