# Generated by Django 2.2.12 on 2020-08-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
