# Generated by Django 2.2.12 on 2020-05-05 20:09

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200502_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='source',
            field=models.ForeignKey(default=api.models.get_default_source, on_delete=django.db.models.deletion.CASCADE, related_name='api_submission_related', to='api.Source'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='source',
            field=models.ForeignKey(default=api.models.get_default_source, on_delete=django.db.models.deletion.CASCADE, related_name='api_transcription_related', to='api.Source'),
        ),
    ]
