# Generated by Django 3.1.3 on 2020-11-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_submission_removed_from_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="cannot_ocr",
            field=models.BooleanField(default=False),
        ),
    ]
