# Generated by Django 3.2.3 on 2021-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_submission_api_submiss_url_5225f1_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(
                fields=["author", "submission", "original_id", "url", "text"],
                name="api_transcr_author__fbec23_idx",
            ),
        ),
    ]
