# Generated by Django 3.2.3 on 2021-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20210621_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
