# Generated by Django 3.2.10 on 2022-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_submission_nsfw"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="report_reason",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="report_slack_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
