# Generated by Django 3.2.10 on 2022-01-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20220116_1355"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="report_slack_id",
            new_name="report_slack_message_ts",
        ),
        migrations.AddField(
            model_name="submission",
            name="report_slack_channel_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
