# Generated by Django 3.2.12 on 2022-03-04 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0023_alter_transcriptioncheck_moderator"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="source",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="origin",
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="reddit_upvote_filter",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
