# Generated by Django 3.2.12 on 2022-03-06 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_auto_20220304_2015"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
