# Generated by Django 3.2.3 on 2021-06-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20201111_2224"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blossomuser",
            options={},
        ),
        migrations.AddIndex(
            model_name="blossomuser",
            index=models.Index(
                fields=["username", "email"], name="authenticat_usernam_22da7a_idx"
            ),
        ),
    ]
