# Generated by Django 3.2.15 on 2022-08-25 17:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_rename_blacklisted_blossomuser_blocked"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="blossomuser",
            name="authenticat_usernam_22da7a_idx",
        ),
        migrations.AddIndex(
            model_name="blossomuser",
            index=models.Index(fields=["username"], name="user_username_idx"),
        ),
        migrations.AddIndex(
            model_name="blossomuser",
            index=models.Index(
                django.db.models.functions.text.Lower("username"),
                name="user_lower_username_idx",
            ),
        ),
    ]
