# Generated by Django 2.2.11 on 2020-04-25 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blossomuser',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
