# Generated by Django 2.2.7 on 2019-12-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blossom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='engineeringblogpost',
            field=models.BooleanField(default=False, help_text='Mark this post as an engineering blog post.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='standalone_section',
            field=models.BooleanField(default=False),
        ),
    ]
