# Generated by Django 2.2.9 on 2020-01-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blossom', '0003_auto_20191227_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=models.TextField(blank=True, max_length=4294000000, null=True),
        ),
    ]
