# Generated by Django 2.2.9 on 2019-12-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blossom', '0003_auto_20191224_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='post_time',
            new_name='submission_time',
        ),
    ]
