[data]
messages = [
    "Building the tools for a better tomorrow!",
    # haddaway
    "What is love? Baby don't hurt me - don't hurt me, no more",
    # portal 2
    "Science isn't about WHY, it's about WHY NOT!",
    "Space. Space. I'm in space. SPAAAAAAACE!",
    # cinderella
    "Even miracles take a little time.",
    "Just because it's what's done, doesn't mean it's what should be done.",
    # alice in wonderland
    "I give myself very good advice, but I very seldom follow it.",
    # the incredibles
    "I never look back, darling! It distracts me from the now.",
    # finding nemo
    "just keep swimming, just keep swimming...",
    # oregon trail
    "You have died of dysentery.",
    # duke nukem 3d
    "It's time to kick ass and chew bubblegum... and I'm all outta gum.",
    # star fox 64
    "Do a barrel roll!",
    # legend of zelda
    "It’s dangerous to go alone, take this.",
    # super mario bros
    "Thank you Mario! But our Princess is in another castle!",
    # diablo II
    "Stay awhile, and listen!",
    # ocarina of time
    "Hey! Listen!",
]
