name: Static Code Analysis

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
    - uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
    - name: Install Dependencies
      run: |
        sudo apt-get install libjpeg8 libjpeg-dev libpng-dev libpq-dev git -y
        poetry install
    - name: Install latest pyflakes and pycodestyle version
      run: |
        poetry run pip install pyflakes
        poetry run pip install pycodestyle
    - name: Run Static Analysis
      run: |
        /usr/bin/git diff -u ${{ github.event.pull_request.base.sha }} | poetry run flake8 --diff
